version: build{build}

skip_commits:
  files:
    - .travis.yml

environment:
  matrix:
  - MINGW_DIR: mingw64
    MINGW_VER: x86_64-7.2.0-posix-seh-rt_v5-rev1
    WITH_FTDI: ON

clone_folder: c:\dev\pulp-tools
clone_depth: 5

install:
  - git submodule update --init --recursive
  - appveyor DownloadFile https://bintray.com/platformio/dl-packages/download_file?file_path=toolchain-riscv-pulp-windows_amd64-1.70101.180627.tar.gz -FileName riscv-toolchain.tar.gz
  - mkdir C:\riscv-toolchain
  - tar xvf riscv-toolchain.tar.gz -C C:/riscv-toolchain

before_build:
  - set Path=C:\mingw-w64\%MINGW_VER%\%MINGW_DIR%\bin;C:\riscv-toolchain\bin;%Path%
  - git config --global core.autocrlf input
  - g++ --version
  - mingw32-make --version
  - cmake --version
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - cd c:\dev\pulp-tools
  - md build

build_script:
  - cd build
# Note: The CMAKE_INSTALL_PREFIX avoids mingw picking up the git shell (sh). This variable should be
# propagated into all cmake scripts in submodules
  - cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DWithFlasher=ON -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%/install" -DWithFTDI=$WITH_FTDI -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"
  - cmake --build . --target pulp-tools -- VERBOSE=1
  - pulp-debug-bridge-prefix\src\pulp-debug-bridge-build\tests\tcp_test_circ_buf.exe
  - pulp-debug-bridge-prefix\src\pulp-debug-bridge-build\tests\timer_test_ae.exe
  - pulp-debug-bridge-prefix\src\pulp-debug-bridge-build\tests\tcp_events_blocking_test.exe
  - pulp-debug-bridge-prefix\src\pulp-debug-bridge-build\tests\async_test_events.exe
  - pulp-debug-bridge-prefix\src\pulp-debug-bridge-build\tests\asynccall_test_events.exe
  - pulp-debug-bridge-prefix\src\pulp-debug-bridge-build\tests\rsp_test_codec.exe
  - pulp-debug-bridge-prefix\src\pulp-debug-bridge-build\tests\timer_test_events.exe
  - pulp-debug-bridge-prefix\src\pulp-debug-bridge-build\tests\tcp_events_simple_test.exe
  - 7z a pulp-tests-win64.zip pulp-debug-bridge-prefix\src\pulp-debug-bridge-build\tests\*
  - 7z a pulp-tools-win64.zip %APPVEYOR_BUILD_FOLDER%/install/*

artifacts:
  - path: build/pulp-tools-win64.zip
    name: pulp-tools-win64
  - path: build/pulp-tests-win64.zip
    name: pulp-tests-win64

test: off
